apiVersion: v1
kind: Service
metadata:
  name: kibana-exporter
  namespace: elk
  labels:
    app: kibana-exporter
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9114
      targetPort: 9114
      name: http-metrics
  selector:
    app: kibana-exporter