apiVersion: v1
kind: Service
metadata:
  namespace: zabbix
  name: zabbix-server
spec:
  type: NodePort
  selector:
    app: zabbix-server
  ports:
    - name: zabbix-trapper
      port: 10051
      targetPort: 10051
      nodePort: 30051
    - name: zabbix-jmx
      port: 10052
      targetPort: 10052
    - name: snmptrapd
      port: 162
      targetPort: 162

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zabbix
  labels:
    app: zabbix-server
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql
          ports:
            - containerPort: 10051
              name: zabbix-trapper
            - containerPort: 10052
              name: zabbix-jmx
            - containerPort: 162
              name: snmptrapd
          env:
            - name: DB_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER_HOST
                  name: zabbix-app
            - name: DB_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER_PORT
                  name: zabbix-app
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: zabbix-app
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: zabbix-app
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: zabbix-app
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: zabbix-app
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: zabbix-app
            - name: ZBX_ENABLE_SNMP_TRAPS
              valueFrom:
                configMapKeyRef:
                  key: ZBX_ENABLE_SNMP_TRAPS
                  name: zabbix-app
        - name: zabbix-agent
          image: zabbix/zabbix-agent
          ports:
            - containerPort: 10050
          env:
            - name: ZBX_SERVER_HOST
              value: "127.0.0.1"
            - name: ZBX_HOSTNAMEITEM
              valueFrom:
                configMapKeyRef:
                  key: ZBX_HOSTNAMEITEM
                  name: zabbix-app
            - name: ZBX_METADATA
              valueFrom:
                configMapKeyRef:
                  key: ZBX_METADATA
                  name: zabbix-app
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: zabbix-app