apiVersion: v1
kind: Secret
metadata:
  name: zabbix-app
  namespace: zabbix
type: Opaque
data:
  # Default password zabbix
  MYSQL_ROOT_PASSWORD: emFiYml4
  MYSQL_PASSWORD: emFiYml4
  # echo -n 'exporter:exporter@tcp(zabbix-db.zabbix.svc.cluster.local:3306)/' | base64 -w 0
  # DSN format: exporter:exporter@tcp(zabbix-db.zabbix.svc.cluster.local:3306)/
  DATA_SOURCE_NAME: ZXhwb3J0ZXI6ZXhwb3J0ZXJAdGNwKHphYmJpeC1kYi56YWJiaXguc3ZjLmNsdXN0ZXIubG9jYWw6MzMwNikv
  # Default account Admin/zabbix
  ZABBIX_USER: QWRtaW4=
  ZABBIX_PASSWORD: emFiYml4
