apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: gitea
type: Opaque
data:
  username: Z2l0ZWFfYWRtaW4=
  password: Z2l0ZWE=
  GITEA_ADMIN_PASSWORD: Z2l0ZWE=
  GITEA_DB_PASSWORD: Z2l0ZWE=
