apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-app-servicemonitor
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
      app.kubernetes.io/component: application-controller
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 10s
  namespaceSelector:
    matchNames:
      - argocd