apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-exporter-servicemonitor
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mariadb-exporter
  endpoints:
    - port: http-metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - nextcloud