apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opensearch-exporter
  namespace: prometheus
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: opensearch-exporter
  namespaceSelector:
    matchNames:
      - opensearch
  endpoints:
    - port: metrics
      interval: 30s
