apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promtail-servicemonitor
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
  namespaceSelector:
    matchNames:
      - grafana
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
