apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo-servicemonitor
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/name: tempo
  namespaceSelector:
    matchNames:
      - tempo
  endpoints:
    - port: tempo-prom-metrics
      path: /metrics
      interval: 15s
