apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zabbix-exporter-servicemonitor
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: zabbix-exporter
  namespaceSelector:
    matchNames:
      - zabbix
  endpoints:
    - port: http-metrics
      interval: 15s