apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nextcloud
  name: nextcloud 
  labels:
    app: nextcloud 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud 
  template:
    metadata:
      labels:
        app: nextcloud
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9205"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - image: nextcloud
          name: nextcloud 
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis

            - name: MYSQL_HOST
              value: mariadb 

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mariadb-secrets

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadb-secrets

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mariadb-secrets

            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadb-secrets 

            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"

            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: |
                yourdomain.domain.com
                0.0.0.0
            - name: NEXTCLOUD_URL
              value: https://yourdomain.domain.com

            - name: NEXTCLOUD_UPLOAD_MAX_FILESIZE
              value: 4G

            - name: NEXTCLOUD_MAX_FILE_UPLOADS
              value: "20"

                #- name: OVERWRITEPROTOCOL
              #value: https
                
                #- name: NEXTCLOUD_INIT_HTACCESS
              #value: "true"

                #- name: NEXTCLOUD_INIT_LOCK
              #value: "true"
        - name: nextcloud-exporter
          image: ghcr.io/xperimental/nextcloud-exporter:latest
          ports:
            - containerPort: 9205
          env:
            - name: NEXTCLOUD_SERVER
              value: "http://localhost"
            - name: NEXTCLOUD_USERNAME
              value: "admin"
            - name: NEXTCLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadb-secrets 