apiVersion: v1
kind: Service
metadata:
  namespace: rustdesk
  name: rustdesk-hbbr
  labels:
    app: rustdesk
    component: hbbr
spec:
  type: NodePort
  selector:
    app: rustdesk
    component: hbbr
  ports:
  - name: hbbr-relay
    port: 21117
    targetPort: 21117
    protocol: TCP
    nodePort: {{ .Values.hbbr.nodePort }}