apiVersion: v1
kind: Service
metadata:
  namespace: rustdesk
  name: rustdesk-hbbs
  labels:
    app: rustdesk
    component: hbbs
spec:
  type: NodePort
  selector:
    app: rustdesk
    component: hbbs
  ports:
  - name: rendezvous-tcp
    port: 21116
    targetPort: 21115
    protocol: TCP
  - name: rendezvous-udp
    port: 21116
    targetPort: 21116
    protocol: UDP
    nodePort: 32116
  - name: nat
    port: 21115
    targetPort: 21115
    protocol: TCP
    nodePort: 32115