apiVersion: v1
kind: Service
metadata:
  namespace: zabbix
  labels:
    app: mysql
  name: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql