apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80;
        location /stub_status {
          stub_status;
          allow 127.0.0.1;
          deny all;
        }
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
