apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        resources:
          limits:
            cpu: '0.2'
            memory: 512Mi
          requests:
            cpu: '0.1'
            memory: 128Mi
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-content
            mountPath: /usr/share/nginx/html
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
          - "-nginx.scrape-uri=http://127.0.0.1:80/stub_status"
        ports:
          - containerPort: 9113
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-content
        configMap:
          name: nginx-index-html
