apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx
  name: nginx-index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="pt-BR">
    <body>
      <h1>Hello World!</h1>
    </body>
    </html>