apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nextcloud
  name: mariadb 
  labels:
    app: mariadb 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb 
  template:
    metadata:
      labels:
        app: mariadb 
    spec:
      containers:
      - name: mariadb 
        image: mariadb:latest 
        ports:
          - containerPort: 3306 
        args:
          - --transaction-isolation=READ-COMMITTED
          - --binlog-format=ROW
          - --max-connections=1000
        env:
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MARIADB_DATABASE
                  name: mariadb-secrets

            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MARIADB_PASSWORD
                  name: mariadb-secrets

            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  key: MARIADB_USER
                  name: mariadb-secrets

            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MARIADB_ROOT_PASSWORD
                  name: mariadb-secrets
