apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault-local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/vault
    type: DirectoryOrCreate
