apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vault-local
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-vault-local
  storageClassName: ""
  