apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-exporter
  namespace: nextcloud
  labels:
    app: mariadb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-exporter
  template:
    metadata:
      labels:
        app: mariadb-exporter
    spec:
      containers:
        - name: mariadb-exporter
          image: prom/mysqld-exporter:v0.14.0
          ports:
            - containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: DATA_SOURCE_NAME
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9104
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9104
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
