apiVersion: v1
kind: Service
metadata:
  name: nextcloud-exporter
  namespace: nextcloud
  labels:
    app: nextcloud-exporter
spec:
  selector:
    app: nextcloud-exporter
  ports:
    - name: http-metrics
      port: 9205
      targetPort: 9205
  type: ClusterIP
