apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: nextcloud
  labels:
    app: redis-exporter
spec:
  ports:
    - name: http-metrics
      port: 9121
      targetPort: 9121
  selector:
    app: redis-exporter