apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: nextcloud
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.61.0
          ports:
            - containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: redis:6379
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 15
            periodSeconds: 15