apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: zabbix
  labels:
    app: mysql-exporter
spec:
  ports:
    - port: 9104
      targetPort: 9104
      name: http-metrics
  selector:
    app: mysql-exporter
  type: ClusterIP