apiVersion: v1
kind: Service
metadata:
  name: zabbix-exporter
  namespace: zabbix
  labels:
    app: zabbix-exporter
spec:
  selector:
    app: zabbix-exporter
  ports:
    - name: http-metrics
      port: 9116
      targetPort: 9116
  type: ClusterIP