apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-exporter
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-exporter
  template:
    metadata:
      labels:
        app: zabbix-exporter
    spec:
      containers:
      - name: zabbix-exporter
        image: python:3.11-alpine
        command: ["/bin/sh"]
        args:
          - -c
          - |
            apk add --no-cache curl && \
            pip install --no-cache-dir requests && \
            python /app/zabbix_exporter.py
        ports:
        - containerPort: 9116
          name: metrics
        env:
        - name: ZABBIX_API_URL
          value: "http://web.zabbix.svc.cluster.local"
        - name: ZABBIX_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-app
              key: ZABBIX_USER
        - name: ZABBIX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-app
              key: ZABBIX_PASSWORD
        - name: PORT
          value: "9116"
        volumeMounts:
        - name: config
          mountPath: /app
        livenessProbe:
          httpGet:
            path: /health
            port: 9116
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 9116
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        configMap:
          name: zabbix-exporter-config
          defaultMode: 0755