apiVersion: v1
kind: Service
metadata:
  name: filebeat
  namespace: elk
  labels:
    app: filebeat
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5066"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 5066
      targetPort: 5066
  selector:
    app: filebeat
