apiVersion: v1
kind: Service
metadata:
  name: registry-exporter
  namespace: registry
  labels:
    app: registry-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-metrics
      protocol: TCP
  selector:
    app: registry-exporter
  type: ClusterIP