apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-exporter
  namespace: registry
  labels:
    app: registry-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-exporter
  template:
    metadata:
      labels:
        app: registry-exporter
    spec:
      containers:
        - name: registry-exporter
          image: yourdomain.domain.com/registry-exporter:latest
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_URL
              value: "http://registry.registry.svc.cluster.local:5000"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
